---
name: Lint Go

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, master]
    paths:
      - "**.go"
      - ".github/workflows/lint-go.yaml"
  pull_request:
    branches: [main, master]
    paths:
      - "**.go"
      - ".github/workflows/lint-go.yaml"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: read

jobs:

  lintGo:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "src/gabo/go.mod"

      # Ref: https://github.com/actions/cache/blob/main/examples.md#go---modules
      # Warning: This is Linux specific
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601  # v9.1.0
        with:
          # We use cache provided by "actions/setup-go@v6"
          skip-cache: true
          # Directory containing go.mod file
          working-directory: src/gabo

      - name: Run `govulncheck`
        working-directory: src/gabo
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
